# makefile
.PHONY: all generate ensure-tools clean

# Configurable tools and paths (override on the make command line)
PROTOC ?= protoc
PROTO_DIRS ?= proto
PROTO_FILES := $(shell find $(PROTO_DIRS) -name '*.proto')
GO_OUT ?= .
GO_GRPC_OUT ?= .

all: generate

generate: ensure-tools
	$(PROTOC) --go_out=$(GO_OUT) --go-grpc_out=$(GO_GRPC_OUT) $(PROTO_FILES)

ensure-tools:
	@command -v $(PROTOC) >/dev/null 2>&1 || { echo "$(PROTOC) not found. Please install protoc."; exit 1; }
	@command -v protoc-gen-go >/dev/null 2>&1 || go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
	@command -v protoc-gen-go-grpc >/dev/null 2>&1 || go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

clean:
	@echo "No autogenerated files are removed by default. Override GO_OUT/GO_GRPC_OUT and add removal rules if needed."